### ISSUE TITLE
Node Version suggestion

### ISSUE THREAD

**Issue by phadtrapong** [Adyen/adyen-3ds2-js-utils#6]
Could you please also suggest the version of node.js that work for the development of this code base?
thank you

**Comment by KrekkieD** [comment]
For base64 it's using `window.atob` and `window.btoa`, so that won't work. I don't think Nodejs is currently a target for the utils.

**Comment by Trigalti** [comment]
We are working on this repository in node v8 and started working on it in v7, but I could not tell you which version is recommended, since indeed, it depends on the local environment you have.
Some of the dependencies are probably v6 or v7 plus.

As @KrekkieD mentioned, the built files are intended for browser usage.
